workflows:
  sample-workflow:
    name: Weather app
    max_build_duration: 120
    instance_type: mac_mini_m1
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - shyamnepal595@gmail.com
          - shyamnepal598@gmail.com