import 'dart:convert';
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:http/http.dart';
import 'package:weaterhui/module/current_weather.dart';

class currentWeatherProvider extends ChangeNotifier {
  Future searchData(String city) async {
    try {
      var response = await get(
          Uri.parse(
              "https://weatherapi-com.p.rapidapi.com/current.json?q=$city"),
          headers: {
            "X-RapidAPI-Host": "weatherapi-com.p.rapidapi.com",
            "X-RapidAPI-Key":
                "d3f7088ea3msh20be116c86008d7p1dc4c2jsn3ba0c68fb6b6"
          });

      notifyListeners();
      if (response.statusCode != 400) {
        return Autogenerated.fromJson(jsonDecode(response.body));
      } else {
        throw HttpException(jsonDecode(response.body));
      }
    } on SocketException catch (e) {
      throw HttpException(e.message);
    } catch (err) {
      throw Exception(err.toString());
    }
  }
}
